name: Build all

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin # timezone
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@54b32c7d11363cad45838c9a3d8a8560b93f0e8c # v1.5.4
      - if: ${{ hashFiles('./package.json')!=null }}
        id: node
        uses: it-at-m/lhm_actions/action-templates/actions/action-npm-build@54b32c7d11363cad45838c9a3d8a8560b93f0e8c # v1.5.4
        with:
          app-path: ""
      - if: ${{ hashFiles('./pom.xml')!=null }}
        id: maven
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-build@54b32c7d11363cad45838c9a3d8a8560b93f0e8c # v1.5.4
        with:
          app-path: ""
